In [1]:
#Shengping jiang 6.2.1 exercises

In [2]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt

In [4]:
cols = ['loan_amnt','int_rate', 'installment']
data = pd.read_csv('loan.csv', nrows=30000, usecols=cols)

In [5]:
data.describe()

          loan_amnt      int_rate   installment
count  30000.000000  30000.000000  30000.000000
mean   15941.940000     12.948691    461.282355
std    10257.787699      4.880157    287.407671
min     1000.000000      6.000000     30.640000
25%     8000.000000      8.810000    248.400000
50%    13800.000000     11.800000    380.660000
75%    22000.000000     16.140000    622.700000
max    40000.000000     30.840000   1618.240000

In [8]:
data.head()

   loan_amnt  int_rate  installment
0       2500     13.56        84.92
1      30000     18.94       777.23
2       5000     17.97       180.69
3       4000     18.94       146.51
4      30000     16.14       731.78

In [7]:
# Standardization--standard deviation(标准偏差)
# Calculate mean and standard deviation values (μ and σ)

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler() 
data_scaled = scaler.fit_transform(data)

print(data_scaled.mean(axis=0))
print(data_scaled.std(axis=0))

[-8.71599089e-17  1.77635684e-18  3.03164901e-17]
[1. 1. 1.]

In [9]:
print('Min values (Loan Amount, Int rate and Installment): ', data_scaled.min(axis=0))
print('Max values (Loan Amount, Int rate and Installment): ', data_scaled.max(axis=0))

Min values (Loan Amount, Int rate and Installment):  [-1.4566678  -1.42389012 -1.49839262]
Max values (Loan Amount, Int rate and Installment):  [2.34538496 3.66619529 4.02556036]

In [12]:
data_scaled[:10]

array([[-1.310435  ,  0.12526631, -1.30952882],
       [ 1.37049964,  1.22770831,  1.09931969],
       [-1.06671367,  1.02894089, -0.97630321],
       [-1.1642022 ,  1.22770831, -1.09523034],
       [ 1.37049964,  0.65394667,  0.94117931],
       [-1.01309498,  0.42444202, -0.93538504],
       [-1.35917927,  1.02894089, -1.35350889],
       [-0.96922514,  0.12526631, -0.89592823],
       [-1.06671367,  1.02894089, -0.97630321],
       [-0.96922514,  0.31173884, -0.88670773]])

In [13]:
# Robust Scalar (Scaling to median and quantiles)
from sklearn.preprocessing import RobustScaler
scaler = RobustScaler() 
data_scaled = scaler.fit_transform(data)

In [16]:
print('Robust scaler mean and std:', data_scaled.mean(axis=0), data_scaled.std(axis=0))

Robust scaler mean and std: [0.15299571 0.15671091 0.21539502] [0.73268691 0.66576743 0.76784099]

In [17]:
print('Min (Loan Amount, Int rate and Installment): ', data_scaled.min(axis=0))
print('Max (Loan Amount, Int rate and Installment): ', data_scaled.max(axis=0))

Min (Loan Amount, Int rate and Installment):  [-0.91428571 -0.79126876 -0.93513225]
Max (Loan Amount, Int rate and Installment):  [1.87142857 2.59754434 3.30638525]

In [42]:
#6.2.4 Shengping Jiang duplicated values exercisers
#cols = ['user_id','age','gender','occupation','zip_code']
orders = pd.read_table('http://bit.ly/chiporders')

In [43]:
orders.shape

(4622, 5)

In [44]:
orders.item_name.duplicated()[:10]

0    False
1    False
2    False
3    False
4    False
5     True
6    False
7    False
8    False
9     True
Name: item_name, dtype: bool

In [30]:
orders.item_name.duplicated().sum()

4572

In [32]:
orders.duplicated().sum()

59

In [46]:
orders.loc[orders.duplicated(),:]

,order_id,quantity,item_name,choice_description,item_price
238,103,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Rice, Black Beans...",$11.75
248,108,1,Canned Soda,[Mountain Dew],$1.09
297,129,1,Steak Burrito,"[Tomatillo Green Chili Salsa, [Rice, Cheese, G...",$11.75
381,165,1,Canned Soft Drink,[Coke],$1.25
484,205,1,Chicken Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$8.75
567,233,1,Canned Soft Drink,[Diet Coke],$1.25
617,254,1,Chips,NaN,$2.15
684,282,1,Canned Soft Drink,[Coke],$1.25
773,319,1,Chicken Bowl,"[Tomatillo-Green Chili Salsa (Medium), Black B...",$8.49
908,376,1,Steak Burrito,"[Roasted Chili Corn Salsa (Medium), [Rice, Faj...",$8.99
924,381,1,Chicken Soft Tacos,"[Tomatillo-Red Chili Salsa (Hot), Cheese]",$8.49
1003,412,1,Bottled Water,NaN,$1.50
1117,462,1,Chicken Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",$11.25
1203,491,1,Chicken Burrito,"[Fresh Tomato Salsa, [Cheese, Sour Cream, Lett...",$8.75
1245,507,1,Canned Soft Drink,[Lemonade],$1.25
1381,561,1,Canned Soft Drink,[Coke],$1.25
1410,573,1,Bottled Water,NaN,$1.50
1420,576,1,Barbacoa Bowl,[Roasted Chili Corn Salsa],$9.25
1421,576,1,Barbacoa Salad Bowl,[Roasted Chili Corn Salsa],$9.39
1502,610,1,Chicken Burrito,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$8.75
1534,624,1,Chips and Tomatillo-Red Chili Salsa,NaN,$2.39
1548,628,1,Chips and Guacamole,NaN,$4.45
1612,651,1,Izze,[Blackberry],$3.39
1791,724,1,Canned Soft Drink,[Coke],$1.25
1792,724,1,Canned Soft Drink,[Coke],$1.25
2078,838,1,Chicken Soft Tacos,"[Fresh Tomato Salsa, [Cheese, Sour Cream, Lett...",$8.75
2127,856,1,Chicken Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",$11.25
2307,926,1,Chicken Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",$8.75
2318,926,1,Chicken Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",$8.75
2362,940,1,Canned Soft Drink,[Coke],$1.25
2448,972,1,Chicken Bowl,"[Tomatillo Red Chili Salsa, [Rice, Black Beans...",$8.75
2553,1011,1,Canned Soft Drink,[Coke],$1.25
2554,1011,1,Canned Soft Drink,[Coke],$1.25
2560,1013,1,Chips and Guacamole,NaN,$4.45
2576,1020,1,Chips and Tomatillo Red Chili Salsa,NaN,$2.95
2662,1057,1,Chicken Soft Tacos,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.25
2708,1074,1,Chips,NaN,$2.15
2717,1078,1,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",$11.25
2833,1125,1,Chicken Burrito,"[Fresh Tomato Salsa, [Rice, Cheese, Lettuce]]",$8.75
2881,1144,1,Bottled Water,NaN,$1.50
2973,1182,1,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Rice, Black...",$8.49
2977,1184,1,Steak Bowl,"[Fresh Tomato Salsa, [Rice, Pinto Beans, Chees...",$9.25
3121,1244,1,Chips and Guacamole,NaN,$4.45
3430,1377,1,Chips and Tomatillo Red Chili Salsa,NaN,$2.95
3637,1454,1,Chicken Soft Tacos,"[Fresh Tomato Salsa, Rice]",$8.75
3716,1484,1,Canned Soda,[Dr. Pepper],$1.09
3764,1507,1,Chicken Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",$8.75
3829,1534,1,Chicken Burrito,"[Fresh Tomato Salsa, [Rice, Cheese, Sour Cream...",$8.75
3924,1574,1,Bottled Water,NaN,$1.50
4112,1647,1,Chicken Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$11.25
4155,1660,1,Chips and Guacamole,NaN,$4.45
4236,1691,1,Chicken Bowl,[White Rice],$8.50
4266,1701,1,Chips,NaN,$2.15
4372,1745,1,Chips and Guacamole,NaN,$4.45
4463,1778,1,Canned Soft Drink,[Lemonade],$1.25
4479,1785,1,Bottled Water,NaN,$1.50
4544,1806,1,Bottled Water,NaN,$1.50
4570,1817,1,Bottled Water,NaN,$1.50
4603,1827,1,Barbacoa Burrito,[Tomatillo Green Chili Salsa],$9.25

In [35]:
orders[orders.duplicated()][:10]

,order_id,quantity,item_name,choice_description,item_price
238,103,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Rice, Black Beans...",$11.75
248,108,1,Canned Soda,[Mountain Dew],$1.09
297,129,1,Steak Burrito,"[Tomatillo Green Chili Salsa, [Rice, Cheese, G...",$11.75
381,165,1,Canned Soft Drink,[Coke],$1.25
484,205,1,Chicken Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$8.75
567,233,1,Canned Soft Drink,[Diet Coke],$1.25
617,254,1,Chips,NaN,$2.15
684,282,1,Canned Soft Drink,[Coke],$1.25
773,319,1,Chicken Bowl,"[Tomatillo-Green Chili Salsa (Medium), Black B...",$8.49
908,376,1,Steak Burrito,"[Roasted Chili Corn Salsa (Medium), [Rice, Faj...",$8.99

In [47]:
orders.duplicated().sum()

59

In [48]:
dup_rows = orders[orders.duplicated()]
print(dup_rows.shape)
dup_rows[:]

(59, 5)

,order_id,quantity,item_name,choice_description,item_price
238,103,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Rice, Black Beans...",$11.75
248,108,1,Canned Soda,[Mountain Dew],$1.09
297,129,1,Steak Burrito,"[Tomatillo Green Chili Salsa, [Rice, Cheese, G...",$11.75
381,165,1,Canned Soft Drink,[Coke],$1.25
484,205,1,Chicken Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$8.75
567,233,1,Canned Soft Drink,[Diet Coke],$1.25
617,254,1,Chips,NaN,$2.15
684,282,1,Canned Soft Drink,[Coke],$1.25
773,319,1,Chicken Bowl,"[Tomatillo-Green Chili Salsa (Medium), Black B...",$8.49
908,376,1,Steak Burrito,"[Roasted Chili Corn Salsa (Medium), [Rice, Faj...",$8.99
924,381,1,Chicken Soft Tacos,"[Tomatillo-Red Chili Salsa (Hot), Cheese]",$8.49
1003,412,1,Bottled Water,NaN,$1.50
1117,462,1,Chicken Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",$11.25
1203,491,1,Chicken Burrito,"[Fresh Tomato Salsa, [Cheese, Sour Cream, Lett...",$8.75
1245,507,1,Canned Soft Drink,[Lemonade],$1.25
1381,561,1,Canned Soft Drink,[Coke],$1.25
1410,573,1,Bottled Water,NaN,$1.50
1420,576,1,Barbacoa Bowl,[Roasted Chili Corn Salsa],$9.25
1421,576,1,Barbacoa Salad Bowl,[Roasted Chili Corn Salsa],$9.39
1502,610,1,Chicken Burrito,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$8.75
1534,624,1,Chips and Tomatillo-Red Chili Salsa,NaN,$2.39
1548,628,1,Chips and Guacamole,NaN,$4.45
1612,651,1,Izze,[Blackberry],$3.39
1791,724,1,Canned Soft Drink,[Coke],$1.25
1792,724,1,Canned Soft Drink,[Coke],$1.25
2078,838,1,Chicken Soft Tacos,"[Fresh Tomato Salsa, [Cheese, Sour Cream, Lett...",$8.75
2127,856,1,Chicken Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",$11.25
2307,926,1,Chicken Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",$8.75
2318,926,1,Chicken Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",$8.75
2362,940,1,Canned Soft Drink,[Coke],$1.25
2448,972,1,Chicken Bowl,"[Tomatillo Red Chili Salsa, [Rice, Black Beans...",$8.75
2553,1011,1,Canned Soft Drink,[Coke],$1.25
2554,1011,1,Canned Soft Drink,[Coke],$1.25
2560,1013,1,Chips and Guacamole,NaN,$4.45
2576,1020,1,Chips and Tomatillo Red Chili Salsa,NaN,$2.95
2662,1057,1,Chicken Soft Tacos,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.25
2708,1074,1,Chips,NaN,$2.15
2717,1078,1,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",$11.25
2833,1125,1,Chicken Burrito,"[Fresh Tomato Salsa, [Rice, Cheese, Lettuce]]",$8.75
2881,1144,1,Bottled Water,NaN,$1.50
2973,1182,1,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Rice, Black...",$8.49
2977,1184,1,Steak Bowl,"[Fresh Tomato Salsa, [Rice, Pinto Beans, Chees...",$9.25
3121,1244,1,Chips and Guacamole,NaN,$4.45
3430,1377,1,Chips and Tomatillo Red Chili Salsa,NaN,$2.95
3637,1454,1,Chicken Soft Tacos,"[Fresh Tomato Salsa, Rice]",$8.75
3716,1484,1,Canned Soda,[Dr. Pepper],$1.09
3764,1507,1,Chicken Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",$8.75
3829,1534,1,Chicken Burrito,"[Fresh Tomato Salsa, [Rice, Cheese, Sour Cream...",$8.75
3924,1574,1,Bottled Water,NaN,$1.50
4112,1647,1,Chicken Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$11.25
4155,1660,1,Chips and Guacamole,NaN,$4.45
4236,1691,1,Chicken Bowl,[White Rice],$8.50
4266,1701,1,Chips,NaN,$2.15
4372,1745,1,Chips and Guacamole,NaN,$4.45
4463,1778,1,Canned Soft Drink,[Lemonade],$1.25
4479,1785,1,Bottled Water,NaN,$1.50
4544,1806,1,Bottled Water,NaN,$1.50
4570,1817,1,Bottled Water,NaN,$1.50
4603,1827,1,Barbacoa Burrito,[Tomatillo Green Chili Salsa],$9.25

In [51]:
orders_dropped_dup = orders.drop_duplicates()

In [52]:
orders_dropped_dup.shape

(4563, 5)